# You can create an virtual running environment with
# Conda package management system. To do this, simply
# install Conda and run following command:
#
# conda env create -f environment.yml
#
# This should install all required Python packages.

name: kimppalotto

channels:
 - anaconda

dependencies:
 - matplotlib
 - numpy
 - pandas
 - seaborn
 - yfinance
 - python=3.6